### ISSUE TITLE
Cannot install pycometh

### ISSUE THREAD

**Issue by rowanhowellGE** [snajder-r/pycoMeth#1]
Hi,

I am trying to install pycometh in a Docker image but I can't get it to install. As a minimal example, try this dockerfile 
`
FROM condaforge/mambaforge

RUN mamba install -c aleg -c plotly -c bioconda -c anaconda pycometh
`

This gives the following error:
>  [2/2] RUN mamba install -c aleg -c plotly -c bioconda -c anaconda pycometh:                                                                                  
> #6 7.760                                                                                                                                                        
> #6 7.760 Looking for: ['pycometh']                                                                                                                              
> #6 7.760 
> #6 7.760 
> #6 7.760 Pinned packages:
> #6 7.760   - python 3.10.*
> #6 7.760 
> #6 7.760 
> #6 7.760 Encountered problems while solving:
> #6 7.760   - nothing provides openssl >=1.0.2p,<1.0.3a needed by python-3.6.7-hd21baee_1002

openssl is part of anaconda channel, so not sure why this can't be installed. 

Any advice appreciated!

**Comment by snajder-r** [comment]
Sorry, I hadn't realized that GitHub wasn't set up to alert me of new issues, so this remained unseen for far too long.

Check out the Readme for the updated installation instructions.
