### ISSUE TITLE
Plans to make pycoMeth compatible with Modkit bedMethyl format?

### ISSUE THREAD

**Issue by bernardo-heberle** [snajder-r/pycoMeth#10]
Hello,

Because of the improvements in modified basecalling accuracy `Nanopolish` states that it does not support R10 flowcells on its GitHub. It also seems that Oxford Nanopore is investing in this new tool suite called [Modkit](https://github.com/nanoporetech/modkit) for analysis of base modification. I was wondering if there are any plans for pycoMeth to start supporting the `bedMethyl` files created by the `pileup` function from `modkit`? Alternatively, do you know of a way to convert the `bedMethyl` files from `modkit` into the `MetH5` format from `Nanopolish` so that they are compatible with `pycoMeth`?

I really like the ease of use and great features included in pycoMeth. It would be great to be able to easily integrate it with the new R10 data pre-processed using `modkit`.

**Comment by SkabbiVML** [comment]
Hi

I came here with the same question, doesn't look like there is an answer to this yet. @bernardo-heberle , have you found a way to perform differential methylation analysis on data generated via R10 flow-cells and modkit?

Cheers

Skabbi

**Comment by bernardo-heberle** [comment]
Hi Skabbi,

I got no answer for this. It looks like modkit does have a module for differential methylation analysis in their documentation under `1.11. Perform differential methylation scoring` - https://nanoporetech.github.io/modkit/intro_dmr.html. You could use that and then generate the visualization for the results on your own. That is what I am planning on doing.

I have not had the time to dig deep into this yet, if I find a way to make the output from modkit compatible with pycoMeth I will post an update here. But to be honest that is pretty low on my priority list right now so it might be a while.

Cheers,
Bernardo

**Comment by SkabbiVML** [comment]
Hei, thanks for the reply @bernardo-heberle!
The modkit documentation is offline atm but I'll keep it in mind and hope to try.

Thanks again

Skabbi
