### ISSUE TITLE
Cannot access pycoMeth documentation

### ISSUE THREAD

**Issue by madagiurgiu25** [snajder-r/pycoMeth#2]
Dear Rene,

I cannot access the [pycoMeth documentation](https://snajder-r.github.io/pycoMeth/).
Best,
Madalina

**Comment by snajder-r** [comment]
Hi Madalina! Sorry, I hadn't realized that GitHub wasn't set up to send me notifications for new issue, so I hadn't seen it until now. Fixed now.
