### ISSUE TITLE
OSError: Unable to open file

### ISSUE THREAD

**Issue by xiaohuli-45** [snajder-r/pycoMeth#8]
Hi, 
I'm running command "pycometh Meth_Seg" and encountering an error:

OSError: Unable to open file (unable to open file: name = '[/NAS/wg_hl/pancancer/OSCC/Methylation/f5c_meth/pycoMeth/MetH5/OSCC1/OSCC1_methylate.m5,', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0).

But my file is existing. I don't know how to solve this issue, can you help me?

**Comment by xiaohuli-45** [comment]
Another issue:
File "/home/wg_hl/miniconda3/envs/Methylation/lib/python3.8/site-packages/pycoMeth/meth_seg/math.py", line 86, in compute_differential_methylation
    good_sites = ((~np.isnan(a_nan)).sum(axis=0) > 0) & (
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

How should I do it?

**Comment by PanZiwei** [comment]
Hi @xiaohuli-45 I encountered the same issue for the `TypeErrorufunc 'isnan' `, do you solve the issue later? Any hints to solve it? Thanks!
