### ISSUE TITLE
Cannot import dependencies required for static image export

### ISSUE THREAD

**Issue by xiaohuli-45** [snajder-r/pycoMeth#9]
Hi, an error was appeared when I run 'pycoMeth Comp_Report'：
'Cannot import dependencies required for static image export'. I noticed that this error occurred when I installed the software and ran the ‘pycoMeth  -h’ command.

Can you help me? Thank you !

**Comment by ChloeL2023** [comment]
Hi @xiaohuli-45  
I also got the sane error. Could you tell me how to fix it? Thanks!
